name: Check C++ Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: init submodules
      run: git submodule update --init --recursive
    - name: configure (Ubuntu)
      if: matrix.os != 'macos-latest' 
      run: sudo apt-get install libeigen3-dev
    - name: configure (macos)
      if: matrix.os == 'macos-latest' 
      run: brew install eigen
    - name: Make build executable
      run: chmod +x .build.sh
    - name: build
      run: ./.build.sh
