name: Check C++ Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']

    steps:
    - uses: actions/checkout@v3
    - name: init submodules
      run: git submodule update --init --recursive
    - name: configure
      run: sudo apt install libeigen3-dev
    - name: Make build executable
      run: chmod +x .build.sh
    - name: build
      run: ./.build.sh
