name: Check Python Wrapper

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: init submodules
      run: git submodule update --init --recursive
    - name: Make test executable
      run: |
       chmod +x test_python_wrapper.sh
    - name: build
      run: ./test_python_wrapper.sh

    - name: Rename wheel (Ubuntu Only)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt install rename
        cd dist
        rename 's/linux/manylinux1/' *
        cd ..
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
